on: [push]

jobs:
  badge_job:
    runs-on: ubuntu-latest
    name: Testing BYOB
    steps:
      - id: date
        run: echo "##[set-output name=data;]$(date)"
      - id: machine
        run: echo "##[set-output name=data;]$(hostname)"
      - id: size
        run: echo "##[set-output name=data;]$(du -sh . | sed 's/[^0-9a-zA-Z]//g')"
      - name: Time badge
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: time
          LABEL: 'Updated at'
          STATUS: ${{ steps.date.outputs.data }}
          COLOR: 00EEFF
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Machine Badge
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: machine
          LABEL: 'Hostname'
          STATUS: ${{ steps.machine.outputs.data }}
          COLOR: FFC0CB
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Size Badge
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: size
          LABEL: 'Repo Size'
          STATUS: ${{ steps.size.outputs.data }}
          COLOR: 00FF00
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: First Icon
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: github
          LABEL: 'GitHub'
          ICON: 'github'
          STATUS: 'BYOBTest'
          COLOR: blue
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Labeless Icon
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: git
          ICON: 'git'
          STATUS: 'Git'
          COLOR: red
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Custom Icon
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: custom
          ICON: 'https://raw.githubusercontent.com/RubbaBoy/BYOBTest/master/icons/dollar.svg'
          STATUS: 'Custom Icons'
          COLOR: red
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Inline Icon
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: custom_inline
          ICON: 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIGhlaWdodD0iMjRweCIgdmlld0JveD0iMCAwIDI0IDI0IiB3aWR0aD0iMjRweCIgZmlsbD0iI0YwMCI+PHBhdGggZD0iTTAgMGgyNHYyNEgweiIgZmlsbD0ibm9uZSIvPjxwYXRoIGQ9Ik0xMiAyMS4zNWwtMS40NS0xLjMyQzUuNCAxNS4zNiAyIDEyLjI4IDIgOC41IDIgNS40MiA0LjQyIDMgNy41IDNjMS43NCAwIDMuNDEuODEgNC41IDIuMDlDMTMuMDkgMy44MSAxNC43NiAzIDE2LjUgMyAxOS41OCAzIDIyIDUuNDIgMjIgOC41YzAgMy43OC0zLjQgNi44Ni04LjU1IDExLjU0TDEyIDIxLjM1eiIvPjwvc3ZnPg=='
          STATUS: 'Inline Base64 Icons'
          COLOR: blue
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
